#!/usr/bin/env bash
set -euo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

if [[ "${BUILDKITE_AGENT_META_DATA_CAPABLE_OF_BUILDING}" == "gdk-for-unity" ]] && [[ "${BUILDKITE_AGENT_META_DATA_OS}" != "linux" ]]; then
  spatial auth login --log_level debug

  if [[ "${BUILDKITE_AGENT_META_DATA_OS}" == "windows" ]]; then
    ACCELERATOR_ENDPOINT="unity-accelerator.production-intinf-eu1.i8e.io"
  fi

  if [[ "${BUILDKITE_AGENT_META_DATA_OS}" == "macos" ]]; then
    ACCELERATOR_ENDPOINT="172.16.100.150"
  fi
fi
